site_information:
  title: ACAP
  description: "Autistic Community Activity Program | Education through recreation"
  logo: /assets/logo.png

navigation_items:
  - label: About
    url: /about.html
  - label: Blog
    children: # No URL specified here since it's just a branch node without a page associated with it
      - label: Posts
        url: /blog.html
      - label: Tags
        url: /tags.html
